### ISSUE TITLE
Project Update And Appreciation

### ISSUE THREAD

**Issue by Ridwanullahi-code** [ReemMohamedAbdelfatah/Portfolio-Reem#11]
Good job @ReemMohamedAbdelfatah 👍 

- [ ] Professional Readme file layout
- [ ] Semantic usage
- [ ] Correct GitHub flow
- [ ] No linter errors
- [ ] Good web accessibility

It will be nice and make your project accessible by changing the following things: 

- [x] Kindly apply ``.active`` , ``focus``  pseudo-class selector to page's buttons.
- [x] It will be nice if you can change the ``value`` of <code>textarea</code> property to the ``placeholder``.

**Comment by ReemMohamedAbdelfatah** [comment]
Thank you @Ridwanullahi-code for helping me improve.
