### ISSUE TITLE
Peer To Peer Code Review

### ISSUE THREAD

**Issue by BlakeYall** [ReemMohamedAbdelfatah/Portfolio-Reem#12]
- [x] Hey Reem, your design looks very good 👍 one of the best designs I've currently seen 💯 however 
       there are a few things to work on. 

       I noticed the paragraph in your contact form is not properly aligned with the contact box and your 
       last card's counter (small circle) has to be properly positioned to fit the figma design 💯

       Once you work on those, your Portfolio will look extra good 👍 
       Thank you and happy coding !

**Comment by ReemMohamedAbdelfatah** [comment]
Thank you @BlakeYall for helping me improve.
