### ISSUE TITLE
Removing nav list items on desktop version

### ISSUE THREAD

**Issue by keebot-png** [ReemMohamedAbdelfatah/Portfolio-Reem#15]
Great work @ReemMohamedAbdelfatah, the portfolio looks professional and very neat. However, you will have to sort out a few issues before you can move on.
  **Changes required include:**

-- Put navigation items in the mobile menu as display none in your media query so that it does not display on the desktop version.

Keep pushing you almost there💪 Just implement the changes required and you will be a few steps closer to completing the project.
Well done!!

**Comment by ReemMohamedAbdelfatah** [comment]
thank you @keebot-png  for helping me improve 😊
