### ISSUE TITLE
Peer-to-peer code review in the mobile version

### ISSUE THREAD

**Issue by norbiboy1** [ReemMohamedAbdelfatah/Portfolio-Reem#4]
Hi @ReemMohamedAbdelfatah 👏 👍 

### Acknowledgments 💯 
- your portfolio is designed very well
- you worked hard for the mobile version skeleton

### Some changes required ♻️ 
- ✅ kindly check your position and alignment of the contact form section.
- ✅ kindly add responsive design for the social media icons.
- ✅ add hover and active(enable) effect to your buttons.
- ✅ the whole section needs to be aligned like in your template.

**Comment by ReemMohamedAbdelfatah** [comment]
Hello @norbiboy1,
Thank you for your review I did make your suggested changes.
