### ISSUE TITLE
Peer-to-peer code review on your desktop-version branch

### ISSUE THREAD

**Issue by norbiboy1** [ReemMohamedAbdelfatah/Portfolio-Reem#7]
Hi @ReemMohamedAbdelfatah 👏 👍 

### Acknowledgments
✅ Your design looks professional and well stylized.
✅ No linter errors.
✅ Good Readme file.
✅ Well done.

- To go forward you had to check the desktop version media query for some issue:
✅ Put max-width on your desktop version screen to align without overflow-x.

**Comment by ReemMohamedAbdelfatah** [comment]
Thank you for your advice. I have Correct the required changes.
